server:
  port: 8767

spring:
  application:
    name: '@project.name@'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projectsdb?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      location: D:/root/gateway_upload_temp
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    fetch-registry: true
